name: Build and Test .NET Application

on:
  push:
    branches:
      - main  # Replace with your main branch name
  pull_request:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner if needed

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.402  # Replace with your desired .NET version

    - name: Restore NuGet Packages
      run: dotnet restore

    - name: Build Application
      run: dotnet build --configuration Release

    - name: Run Tests
      run: dotnet test --configuration Release

    # You can add additional steps as needed, such as publishing artifacts or deploying

